include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"

  errors:
    avoid_classes_with_only_static_members: ignore
    document_ignores: ignore
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    public_member_api_docs: ignore
    sort_pub_dependencies: ignore
    strict_raw_type: ignore

linter:
  rules:
    - prefer_single_quotes
    - avoid_print
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - always_declare_return_types
    - annotate_overrides
    - hash_and_equals
    - sort_constructors_first
    - avoid_field_initializers_in_const_classes
    - avoid_positional_boolean_parameters
    - unnecessary_this
    - avoid_classes_with_only_static_members
