name: hubx_case_study
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-254.0.dev

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0

  #Linter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

  #Env
  envied: ^1.1.1

  #Network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dio_cache_interceptor: ^4.0.3

  #Utils
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  equatable: ^2.0.7
  collection: ^1.19.1

  #Storeage
  shared_preferences: ^2.5.3 

  #Router
  auto_route: ^10.1.0+1

  #State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  envied_generator: ^1.1.1
  auto_route_generator: ^10.2.3
  freezed: ^2.3.4
  json_serializable: ^6.9.5

  

flutter:
  uses-material-design: true
  generate: true


  assets:
  - assets/
  - assets/images/
  - assets/icons/
  - assets/lottie/
  - .env


